nelmio_api_doc:
    documentation:
        info:
            title: Torneo-tenis by Maxi Mohamed
            description: API documentation for the Torneo-tenis project
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api(?!/doc$)
