version: '3.8'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: torneo-tenis-php
    volumes:
      - ../torneo-tenis/:/var/www/html
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "8080:80"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: torneo-tenis-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: torneo
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: torneo-tenis-phpmyadmin
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"

volumes:
  db-data: